<a href="https://colab.research.google.com/github/sisodia91/data-analysis-tasks/blob/main/Task_1_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task 1 - Data Cleaning and Preprocessing

## Objective
Clean and preprocess Amazon product dataset using Python and Pandas.

## Tools Used
- Python
- Pandas
- NumPy
- Google Colab

## Operations Performed
- Dataset exploration
- Handling missing values
- Removing duplicates
- Fixing data types
- Standardizing text formatting
- Saving cleaned dataset

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/amazon.csv')

In [3]:
df.head()
df.info()

df.isnull().sum()
df = df.drop_duplicates()
print("Duplicate Rows:", df.duplicated().sum())
df.fillna("Unknown", inplace=True)
numeric_columns = df.select_dtypes(include=np.number).columns

for col in numeric_columns:
    df[col].fillna(df[col].median(), inplace=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   object
 4   actual_price         1465 non-null   object
 5   discount_percentage  1465 non-null   object
 6   rating               1465 non-null   object
 7   rating_count         1463 non-null   object
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
dtypes: object(16)
memory usage: 183.3+ KB
Duplicate Rows: 0

In [4]:
df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ", "_")

In [5]:
text_columns = df.select_dtypes(include='object').columns

for col in text_columns:
    df[col] = df[col].str.strip()
df.dtypes

product_id             object
product_name           object
category               object
discounted_price       object
actual_price           object
discount_percentage    object
rating                 object
rating_count           object
about_product          object
user_id                object
user_name              object
review_id              object
review_title           object
review_content         object
img_link               object
product_link           object
dtype: object

In [6]:
df['discounted_price'] = df['discounted_price'].replace('[₹,]', '', regex=True).astype(float)

df['actual_price'] = df['actual_price'].replace('[₹,]', '', regex=True).astype(float)
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   float64
 4   actual_price         1465 non-null   float64
 5   discount_percentage  1465 non-null   object
 6   rating               1465 non-null   object
 7   rating_count         1465 non-null   object
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
dtypes: float64(2), object(14)
memory usage: 183.3+ KB

       discounted_price   actual_price
count       1465.000000    1465.000000
mean        3125.310874    5444.990635
std         6944.304394   10874.826864
min           39.000000      39.000000
25%          325.000000     800.000000
50%          799.000000    1650.000000
75%         1999.000000    4295.000000
max        77990.000000  139900.000000

In [7]:
df.to_csv('cleaned_amazon_dataset.csv', index=False)

In [8]:
from google.colab import files

files.download('cleaned_amazon_dataset.csv')